# Generated by Django 5.2.7 on 2025-11-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='img_product',
            new_name='img_producto',
        ),
    ]
