# Generated by Django 5.2.7 on 2025-11-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_img_product_products_img_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img_producto',
        ),
    ]
