# Generated by Django 5.2.7 on 2025-11-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_img_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img_products',
            field=models.URLField(null=True),
        ),
    ]
